apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris-model
  template:
    metadata:
      labels:
        app: iris-model
    spec:
      containers:
      - name: iris-model
        image: your-registry/iris-model:latest
        ports:
        - containerPort: 5000